// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'spin': string;
  'switch': string;
  'switch_button': string;
  'switch_button_active': string;
  'switch_inner': string;
  'switch_large': string;
  'switch_loading_icon': string;
  'switch_medium': string;
  'switch_rail': string;
  'switch_small': string;
}
export const cssExports: CssExports;
export default cssExports;
