// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'carousel': string;
  'carousel__fade': string;
  'carousel_dots': string;
  'carousel_dots_active': string;
  'carousel_dots_dot': string;
  'carousel_dots_line': string;
  'carousel_dots_line_active': string;
  'carousel_dots_vertical': string;
  'carousel_slide': string;
  'carousel_slides': string;
}
export const cssExports: CssExports;
export default cssExports;
